### PR TITLE
Add operator tests from KInference

### PR DESCRIPTION
**Pull request by isomethane**

### CODE REVIEW

**Comment by nbirillo** [comment]
@isomethane could you please merge the operators-shape-inference branch into this one?

**Review by nbirillo — APPROVED** [review]
Great job!

**Comment by nbirillo** [comment]
@isomethane please fix conflicts

**Comment by isomethane** [comment]
@nbirillo fixed

**Comment by nbirillo** [comment]
@isomethane please, fix tests

**Pull request merged**
